### PR TITLE
Add MaxFloat64

### PR DESCRIPTION
**Pull request by DaKnOb**
Add ability to calculate the largest Float64 value as well

### CODE REVIEW

**Comment by DaKnOb** [comment]
Please merge #4 before this. Thanks :)

**Comment by djcass44** [comment]
Hey mate, thanks for the contribution. It looks like this MR contains the entire contents of #4, why wouldn't I just merge this one?

**Comment by DaKnOb** [comment]
Sorry, this has been branched off of #4, and this is the reason, instead of the main branch. Let me know if you want me to remove the `MinFloat64` commit.

**Comment by djcass44** [comment]
> Sorry, this has been branched off of #4, and this is the reason, instead of the main branch. Let me know if you want me to remove the `MinFloat64` commit.

That's not my issue. Why are there 2 merge requests? I'd be happy merging just this one since it contains the full contents

**Comment by djcass44** [comment]
Thanks for the submission, but I'll be closing this and #4 since the code they add is already contained within the GoLang standard library (https://golang.org/pkg/math/#Min).

If you have any other additions, feel free to open another MR

**Pull request closed without merging**
